spring:
  application:
    name: ms-mytaxi-account
  datasource:
    url: "jdbc:postgresql://localhost:5432/db_mytaxi_account"
    username: root
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null
